import string
import networkx as nx
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

translations = ["See’st thou Soracte white with a deepe snow? How the bowed trees their weight can’t undergoe? And how the streams, bound with sharp ice, doe stand? Dissolve the frost, laying with bounteous hand Wood on the fire, and with a courage bold Draw, Thaliarch, thy wine of four years old, Out of thy Sabine two-ear’d pot the rest Leave to the gods, who when they have suppressed The winds on the rude sea maintaining warre, Nor Cypress, nor old Ash-trees shaken are. Enquire thou not what shall to morrow bee, And whatsoever day fortune giveth thee, Put it upon thy gaines; nor sweet love-glances Doe thou abhor, O boy, nor yet our dances. While crabbed age forbears thy youth a space, Let both the martial field and wrestling place, And softly-whispers when the night comes in, At a fit season be revived again; And the maids pleasant laugh that her betrayed Within some private corner closely laid, Or favour being snatched from her arm Or finger having done some trifling harm.",
" Thou seest white Soracts head With deep snows overspread, The over-charged woods to bow, And greatest floods run slow Now shut could out of door By burning wood good store. Let Sabine wines now swim, With bowls filled to the brim, And think it Thaliarck best To th’ Gods to leave the rest Who soon loud winds appease Within the raging Seas, Nor Cypress Against the Ash They ’ile suffer once to dash; Shun thou to pray or see What may tomorrow be, What change each day doth send To profit it commend. Nor scorn (my boy,) sweet love, Nor daunces for to move, Whilst to thy tender years No froward age appears Broad Allies, open fields, By night sweet whispering yields, And in an hour once set These things thou mayst repeat Now in a corner nigh A maid thou mayst espie, Though hid, yet willing shee That laughter makes thee see, And from her a plucked chain She’ll poorly snatch again.",
" Dost thou not see how in one night The fields grow aged, and turn white? The offspring of the Forrest now Putts on a night-capp, and doth bow. The sharper frost lays an arrest Upon faire Avons Liquid brest. Why should we shivering turn with these to ice, When an increase of fire, with Ale and spice May thaw us thoroughly? double then thy pains Thou blinking Ned; lett Leonard fill our veins With the Suns last-years Nectar, better farre Than the Diota, or Sabinian starre. Putt we the rest to God; who makes A war at Sea with windes, yet shakes Neither the Ash, nor Cypress tree; Leave to Curiosity What shall the morrow-work be, and The Gifts of Fortune let's command. Nor whilst the rising sapp proclaims us young, And free from crooked Ages peevish young Lett us refuse to sport, to daunce or sing, Sheltered under Cupids golden wing Now on the Plains with Hound, or Hawke We'll spend the day; at Even the walk Shall our retreat be, where we may discover The whispering repetitions of some Lover? Or hear the inward pretty giglings, beene From a wench in a corner, and not seen? Or see one run away half madd for joy He’d got a Ring from his Mistress, or some toy? Thus, though both woods and fields seem old, And Avon’s frozen up with cold, Whilst there is fire in Venus court We shall not want for heat and sport.",
" Seest thou not, how Soractes Head, (For all it’s Height) stands covered With a white Perriwigg of Snow? Whilst the labouring Woods below Are hardly able to sustain The Weight of Winters feather’d Rain; And the arrested Rivers stand Imprison’d in an Icy Band? Dispel the Cold; and to the Fire Add fuel, large as it’s Desire; And from the Sabine Casque let fly (As free as Liberality) The Grapes rich blood, kept since the sun His Annual Course foure times hath run. Leave to the Gods the rest, who have Allay’d the Winds, did fiercely rave In Battail on the Billowy main, Where they did blustering tug for Raign. So that no slender Cypress now, It’s Spirelike Crown does tottering, bow Nor aged Ashtrees, with the shock Of Blasts impetuous, doe rock. Seek not to morrow’s Fate to know; But what day Fortune shall bestow, Put to a discreet Usurie. Nor (gentle youth!) so rigid be With froward scorn to disapprove The sweeter Blandishments of Love. Nor mirthfull Revels shun, whilst yet Hoary Austerity is set Far from thy greener years; the Field Or Cirque should now thy Pastime yield Now nightly at the Hour select, And pointed Place, Loves Dialect, Soft whispers, should repeated be; And that kind Laughters Treachery, By which some Virgin closely layd In dark Confinement, is betrayed And now from some soft Arm, or Wrist, A silken Braid, or silver Twist, Or Ring from Finger, should be gain’d, By that too nicely not retain’d.",
" Thou seest the Hills candied with Snow Which groaning Woods scarce undergo, And a stiff Ice those veins Congeals which Branch the Plains. Dissolve the Frost with Logs pil’d up To th’ Mantle-tree; let the great Cup Out of a larger Sluice Pour the reviving Juice. Trust Jove with other things; when he The fighting Winds takes up at Sea, Nor speared Cypress shakes, Nor aged Elm-tree quakes. Upon to Morrow reckon not, Then if it comes ’tis clearly got Nor being young despise Or Dancings, or Loves Joys. Till testy Age gray Hairs shall Snow Upon thy Head, lose Masque, nor Show Soft whispers now delight At a set hour by Night And Maids that giggle to discover Where they are hidden to a Lover; And Bracelets, or some Toy Snatcht from the willing Coy.",
" Thou seest Soracte’s lofty summit show, All Candyed or with profound drifts of Snow How th’ Woods scarce their loads sustain, And Ice the fluent streams restrain, Make larger piled-up fires, dissolve the Cold And let delicious liquors four years old Broached be from Sabin Tun, And (Thaliarchus) freely run. All other cares be to the Gods assign’d; Who when th’ave once becalm’d the struggling Wind On fierce seas nor Cypress-tree, Nor aged Elm-tree shaken be. Enquire not what shall be to Morrow’s Fate; And what e’r Fortune shall attend thy date, Count it gain Love’s pleasant Joy, Nor Dances shun, while thou’rt a Boy Til crab’d Old-age thy fresh Complexion stain With hoar hair. Now let Mars his Camp and Plain, And ’bout Twilight, whispers soft Be at set houres rehearsed oft. Now tell how Maidens pleasant laughter use When they’re disclosed from some dark Recluse; And of Bracelets snarcht from wrists, Or Rings from unresisting fists.",
" See how the Hills are white with snow, The Seas are tough, the Woods are tost, The Trees beneath their Burthen bow, And purling Streams are bound in Frost. Dissolve the Cold with noble Wine, Dear Friend, and make a rouzing Fire; ’Gainst Cold without, and Care within, Let both with equal force conspire. With all things else, come, trust the Gods, Who when they shall a Calm restore, And still the Storms that toss the Floods, Old Oaks and Ashes shake no more. All Cares and Fears are fond and vain, Fly vexing Thoughts of dark to-morrow; What Chance scores up, count perfect Gain, And banish Business, banish Sorrow. Whilst Thou art Green, and Gay, and Young, E’er dull Age comes, and Strength decays, Let Mirth, and Humour, Dance, and Song Be all the Trouble of thy Days. The Court, the Mall, the Park, and Stage, With eager Thoughts of Love pursue; Gay Evening Whispers fit thy Age, And be to Assignation true. Now love to hear the hiding Maid, Whom Youth hath fir’d, and Beauty charms, By her own tittering Laugh betray’d, And forc’d into her Loyer’s Arms. Go dally with thy wanton Miss, And from the Willing seeming Coy Or force a Ring, or steal a Kiss, For Age will come, and then farewell to Joy.",
" View’st how Soracte white does wear Deep Shrouds of snow? and Woods appear Through surcharged Branch opprest? Congealed Streams do rest. Come Thaliarch, banish cold, throw on Large piles to th’ Sabine cask anon? Four years Wine thence freely draw, ’T will Winter help to thaw. Leave th’ rest to Gods, who when shall please To ’hush warring Winds and boyling Seas, Nor the old Ash, nor Cypress shall Be tost disturb’d at all. To morrow’s Fates neglect, esteem Each new day gain’d; nor nicer seem Young sweet, pleasing Loves t’advance; Joyn’d hands in Virgin-dance. Ere testy Age befrost thine head, Now Manly fields for Action tread Twilights whispering talk (set hour) Oft steal now from close Bower. Dark nook fine tittering Noise betrays Some Female Wag, in skulking Maze; Pledg from Wrist of Finger taken Forc’d though with ease forsaken.",
" Behold yon’ Mountains hoary height Made higher with new Mounts of Snow; Again behold the Winters weight Oppress the lab’ring Woods below And streams with Icy fetters bound, Benum’d and crampt to solid ground. With well heap’d Logs dissolve the cold, And feed the genial hearth with fires; Produce the Wine, that makes us bold, And sprightly Wit and Love inspires For what hereafter shall betide, God, if ’tis worth his care, provide. Let him alone with what he made, To toss and turn the World below; At his command the storms invade; The winds by his Commission blow Till with a Nod he bids ’em cease, And then the Calm returns, and all is peace. To morrow and her works defie, Lay hold upon the present hour, And snatch the pleasures passing by, To put them out of Fortunes pow’r Nor love, nor love’s delights disdain, What e’re thou get’st to day is gain. Secure those golden early joyes, That Youth unsowr’d with sorrow bears, E’re with’ring time the taste destroyes, With sickness and unwieldy years! For active sports, for pleasing rest, This is the time to be possest; The best is but in season best. The pointed hour of promis’d bliss, The pleasing whisper in the dark, The half unwilling willing kiss, The laugh that guides thee to the mark, When the kind Nymph wou’d coyness feign, And hides but to be found again, These, these are joyes the Gods for Youth ordain.",
" See how Soracte’s Mountain scarce sustains Her hoary Load! what Frosts congeal the Woods, Bind fast the waving Seas in Icy Chains, And stop the rapid Current of the Floods! Now let your Hearth with Piles of Billets glow, The Sabine Casks their mellow Charge diffuse Dissolve the crystal Ice, melt down the Snow With never-ceasing Fires and sparkling Juice. Leave all the rest to Jove, at whose Command The warring Winds their rough Contentions end, No more the Waves in curling Ridges stand, Nor Ash, nor Cypress to the Tempest bend. Nought Future, no To-morrows Thee employ, The present Hour is thine, and this improve, Now in the Youth the Gift of Heaven enjoy, In Sportive Dance, in Revels, and in Love. Remove far off Old-age and late Decay; Now to the Walks and to the Ring repair At Night the lucky Moment calls away, The gentle Whisper, and the yielding Fair. In vain she flies to hide, but laughing shows How you may find her out, and hold her fast And when you snatch some Favour, clap it close, Struggles a-while, but– lets it go at last.",
" Look yonder see Soracte clad in Snow, How cold and comfortless the Mountains show! The Groves, that with becoming Greens are spread, Under their Snowy Burthen hang the Head; And Rivers, that congealing Frosts do bind, Within an Icy Prison are confin’d. Then, Thaliarchus, draw the Wine that’s Old, And make good Fires to keep out the Cold Leave to the Gods the rest; who, when they please, Can calm the Winds, that ruffle on the Seas, And then th’ unshaken Woods will be at ease. Ne’er think on what to Morrow shall produce, But of the present Day and Hour make use, The Gods to thee another may refuse. With kind Embrace thy pleasant Mistress greet, Frequent the Balls where jolly Dancers meet; Whist Youth does hold, be merry, brisk, and gay, ’Twill all be over when thy Hairs are grey. Use martial Exercise whilst in thy Pow’r, And meet at Night to whisper thy Amour; With sportly Maidens play at hide and seek, That tell their Hiding-places by a Squeak; Snatch off their Bracelets, Rings, and Gloves, and then They know those Trinkets thee engage agen.",
" The Moutain of the Delphian God You see is wrapt in Sheets of Snow; The Trees, sustaining scarce their Load, Their hoary Heads dejected bow; And, glew’d with Ice unto the Shore, The active Streams can roll no more. With rousing Fires the Cold destroy, And set about the flowing Bowl; Bled e’ery Grape to give us Joy, To cherish and exalt the Soul. Hereafter to the Gods resign; Be theirs the Care, Enjoyment thine. To them this Earth, their Foot-ball leave To kick and tumble as they please; From them the Storms Permission have To box about the tasty Seas; Yet, still subjected to their Will, If they but nod, are hush and still. To Morrow, and its Cares despise; The present Moment is thine own; Then snatch it quickly ere it flies, And score it up as clearly won; Nor scruple to indulge the Fire Of youthful Love, and gay Desire. Old Age will quickly pall the Taste, And blunt the Edge of sprightly Joys, With dozing Sadness fill the Breast, And give no Relish but for Toys. Youth is alone the Time can prove Delights of Exercise, or Love. The gentle Talk, the soft Embrace In some retir’d, and dusky Shade; The feigning hidden Maid to trace, By her own treach’rous Sneer betray’d; Be these thy Care, thy Business still; Such Pleasures Youth alone can feel. And when with struggling in your Arms, The leering little roguish Thing Is rous’d, and flushing all with Charms, Secure her Hand, and snatch her Ring; Then all her Frowns are but a Blind; ’Tis Pledge enough that she’ll be kind",
" See, see, the Hills are heap’d with Snow, The Forests bend beneath their Load, The Rivers now forget to flow, And turn’d to Chrystal stands the Flood. Be gen’rous, Friend, and melt away The Rigour of the Winter’s Cold; High on the Hearth your Billets lay, And broach your Wine of four Years old. Leave all things to the Gods beside, Disposers of Affairs below, Who give the Word, and Waves subside, And furious Tempests cease to blow. Ne’er, Boy, on dull To-morrow think, But live To-day, and call it Gain; And love and dance, as well as drink, Whilst Youth and blooming Beauty reign. In the great Field of Mars appear, And thine in publick Walks by Day; Make Assignations with the Fair, And pass the Night in am’rous Play. Soon from the Corner, where she lies, Her Titt’ring will the Nymph disclose; Then make her Chain or Ring your Prize, With coming Coyness she’ll oppose.",
" Behold Soracte’s airy height, See how it stands a heap of snow; Behold the winter’s hoary weight Oppress the labouring woods below; And by the season’s icy hand Congeal’d, the lazy rivers stand. Now melt away the winter’s cold, And larger pile the cheerful fire; Bring down the vintage four years old, Whose mellow’d heat can mirth inspire; Then to the guardian powers divine Careless the rest of life resign; For when the warring winds arise, And o’er the fervid ocean sweep, They speak– and lo! the tempest dies On the smooth bosom of the deep; Unshaken stands the aged grove, And feels the providence of Jove. To-morrow with its cares despise, And make the present hour your own, Be swift to catch it as it flies, And score it up as clearly won; Nor let your youth disdain to prove The joys of dancing and of love. Now let the grateful evening shade, The public walks, the public park, An assignation sweetly made With gentle whispers in the dark While age morose thy vigour spares, Be these thy pleasures, these thy cares. The laugh that from the corner flies, The sportive fair one shall betray; Then boldly snatch the joyful prize; A ring or bracelet tear away, While she, not too severely coy, Struggling shall yield the willing toy.",
" See how white the Hills with Snow! Hardly Trees their weight sustain! Rapid Rivers cease to flow, Bound by Winter’s icy chain! Break this Cold, with piles of Wood, Bring the joy-inspiring Flask; Freely draw the gen’rous flood, Four years standing in the Cask. Leave to Heav’n its proper care, Heav’n can still Winds & Sea; When it please, no breath of air, Wags the Ash or Cypress-tree! All your care– the present now Let to morrow come or not Ev’ry year the Fates allow (Few or many) is your lot. Dance I revel, sing & love, Nor from those soft pleasures fly While cold-age shall not reprove, Nor gay-youth its strength deny Now to private walks repair, Am’rous Girls in such delight Short-breath’d murm’rings fill the air, Whisper’s sounds to Love invite. Hid in some dark corner, They Titt’ring see you search about And indulging wanton play, By their laughing are found out. Strugling now for some light Joy Which they mean not to refuse Gentle force you now emply Force enough– for an excuse.",
" See, see around Holt’s hoary brow Heaps pil’d on heaps of shining snow! O’ercharg’d with its enormous load, The lab’ring forest seems to nod; And staunch’d by winter’s magic breath, Streams feel a temporary death. Then load the hearth with lib’ral hand, And bid the cold at distance stand; While from the mellow flask, my friend, Large bumpers of old wine descend. Wisely all other thoughts forbear; Indulgent Jove makes them his care; Indulgent Jove, who bids to sleep The boist’rous storms that vex the deep. He nods, and not a single breeze Is heard to whisper thro’ the trees. To fortune’s wild caprice resign’d, With morrow’s cares ne’er charge the mind; But wisely make to-day your own, And as neat profit put it down. While youth permit it, gaily prove The pleasing mysteries of love Blest with a blooming fair, advance Thro’ all the mazes of the dance. Full soon, alas! will pevish age The curtain drop, and clear the stage. Now is the season of resort To parks and malls for am’rous sport Now favour’d by the dusk of night, To form new scenes of gay delight; And in soft wispers there impart The tender story of the heart. And now the laugh betrays the maid Half hid in some convenient shade; Where, in the wanton strife of love, The youth attempts or ring or glove; Which, tho’ pretending to deny In compliment to modesty, She wishes his; and hopes the boy Will not regard her being coy.",
"See high Soracte, white with snow, Still more and more a mountain grow, Nor can the lab’ring woods their weight sustain, And motionless with frost the sharpen’d streams remain. Dissolve the cold, a rousing fire Upon the social hearth aspire, And four years old with bountiful design Bring in the Sabine jar the long-expected wine. Leave to th’ immortal Gods the rest, For when they shall have once supprest The winds, that on the boiling surge contend, Nor cypress shakes a leaf, nor yon old ash-trees bend. Enquire not of to-morrow’s fate, And whatsoever chance await, Turn to account, nor fly from sweet amours, Nor let the dance be shunn’d by such address as yours. While yet your vig’rous years are green, Nor peevish age brings on the spleen, By turns the field, the tenis-court repeat, And whispers soft at night for assignations meet. Now glad to hear the damsel raise The laugh, that her retreat betrays, Steal from her arm the pledge for theft dispos’d, Or from her finger force, with sham-resistance clos’d.",
" See where Soracte, deep in snow, Erects his hoary lofty brow, The labouring forests scarce sustain The silver load, the floods below Forbid to flow, Fast bound in icy chain. Dissolve the cold, and piling high, O Thaliarch, thy wood log dry, Thy ample bowl, of richest juice Falerny, rising four produce; Warm well thy breast, and leave the rest To providence’s care, To quell at will the fervid seas, Bid battling Aquilonians cease, The placid deep, and forests sleep, And thaw the freezing air. Think not of sorrow, or to-morrow, Whatever more the gods bestow As so much honest gain allow; Nor scorn the dance and choral lays, In flow’ry youth, e’er surly grow All-marring age with wither’d brow, The evening breeze, the waving trees, The assignation in the park, The breathing whisper in the dark, The happy minute seize. When corner’d close, the latent maid Is by her titt’ring laugh betray’d; And snatch the bracelet of the coy, In wily disport bold, Reluctant press’d to yield the toy She never meant to hold.",
" See there how the Lomonds, thick cover’d with snow Stand like fleecy clouds on the valley below, How Melvel and Rankeilor woods bend down, And, with the snow o’erloaded, groan! How Eden’s meanders cold shivering look, Incrusted all over, immovable rock! Come in, come in! Such prospects quickly tire; More coals; make a resplendent fire! A brace of old claret and rum quickly here! A bowl of punch royal our spirits will chear; We’ll with a thorough thaw within be bless’d, And leave to Providence the rest. Whenever it pleases th’ Almighty to lay The boisterous tempests that ravage the sea, No longer forests agitated quake, Nor lofty pines and alders shake. What may be to-morrow’s events never mind Think every day’s chance for advantage design’d Nor you, Sir, in your youthful prime despise Th’ inchanting ball and ladies’ eyes. While peevish old age not approaching you see, And both town and country invite you to glee, And th’ assignation whisper’d soft, At night, Th’ inviting minutes of delight, Precisely attend. In a corner there, hark! A tittering laugh her betrays in the dark Quick snatch the sweet reluctant yielded kiss, And some kind token of your bliss.",
" Behold, opprest with heaps of snow, Soracte shews his tow’ring height; The lab’ring trees, rang’d far below, Can scarce sustain their shining weight The streams in icy chains are bound, And toss’d with raging forms, the seas resound. Dispel the cold with chearful fire, And tap, my friend the farthest cask; The drooping soul with wine inspire, And drown all sorrows in a flask. No more at cares of life repine, But leave events to fate and pow’r divine. The cypress on the mountain brow, The winds that o’er the ocean sweep, The bellowing tempests cease to blow, And peaceful rests the surging deep Quiet remains the silent grove, And all confess the providence of Jove. Tomorrow’s coming cares disdain, And freely use the present hour! The Joys we’ve known are certain gain, We’ll taste the pleasures in our power Let drink and dance, and mirth consume Our days, while health invites and youth’s in bloom. From park to play, we joys pursue, And bless the evening’s happy shade; To love and assignation true, With vig’rous youth we press the maid Uncheck’d by impotence or age, In soft intrigues and gallantries engage. The sportive lass, pretending shame, Within the Covert veils her face; A titt’ring laugh, reveals her flame, And courts you to the secret place; Fly to her arms, an haven of bliss, Steal from the half-coy maid a ring, or snatch a kiss.",
" Thither, O Thaliarchus, turn your eyes, And view at once with wonder and surprize! Look yonder, where the drifts of rigid snow Lie scatter’d thick on bleak Soracte’s brow! Or see you not those trees which downward bend, With the white flakes that on their boughs depend? The rapid running rivers now are staid, Arrested by the frost, asleep they’re laid. May the northern evils far retire, Recruit with faggots the consuming fire, Pour forth the produce of the gen’rous vine, And make the sabine cask it’s store resign; Leave all the rest to the celestial pow’rs, Who rule, just as they will, this world of ours; Who now like mountains toss the foaming seas, And the next moment all is hush’d in peace. Let not the future time thy peace annoy, But what to-day affords, content enjoy, Nor with a shy simplicity evade, A sweet amour, or pleasing masquerade, Until moross old age thy strength envade. Now should the field and place of public shew, And dark intrigues where midnight lovers go, Where sighs unnumber’d mix with common air, Be all attended with exactest care; And now the youth detects the hiding maid, By her own titt’ring laughter soon betray’d; And now the jocund nymph the pledge resigns, Which from her yielding arms her lover twines.",
" Lo, on Soracte’s dreary height The snow with silver mantle gleams; The forests bend beneath its weight, And frost binds up the rapid streams. With high pil’d wood profusely stow Your hearth, and melt stern winter’s rage Let sabine casks benignly flow With juice that owns the power of age. Trust to the Gods the rest, whose care Can bid fierce nature’s conflict cease; When the rude winds the forest tear, Can hush the elements to peace. Seek not to know the bliss or pain That from to-morrow takes its birth; But count each day a present gain; Enjoy sweet love and festal mirth. Ere hoary age your temper sour, Now let the martial plain delight; Let love’s appointments claim their hour, And with soft whispers charm the night. Then, whilst in darkness lurks the fair, Soon by her tittering laugh betray’d, Do thou the shining bracelet bear, Won from the struggling, willing maid.",
"Soon will trees, dear Friend, around With isicles bow low, The frozen earth, like iron bound, Forbid the streams to flow. Fill then the glass, stir up the fire, And chase the cold away; Let wit and chearful mirth conspire To cheat the tedious day. The rest to Providente submit; Nor ask if France or Spain Will treat with Malmesbury or Pitt (Enquiries made in vain). Brave Gardaer’s ships, as tempests roar, In port new shelter find; And now regain the Gallic shore, As Neptune proves more kind. ’Tis Heav’n alone can look into Futurity’s dark night; ’Tis not my Friend, for me or you To dare the curious light. Let others venture, if they will; And future lots divine; So you have Wealth and Beauty still, So calm Content is mine.",
" Behold Soracte’s, distant height Clad with resplendent robes of snow; Behold the winter’s frosty weight Frown o’er the nodding groves below! Each liquid stream, by frost congeal’d, Extends an icy plain afar The zephyrs now to Boreas yield, And nature groans in wintry war. Increase the fire, disperse the cold; And from the jar, my dearest boy, Pour generous wine of four years old, To gladden every heart with joy. Let angry Gods on tempests ride In conflict with the fervid seas; Or bid the furious storm subside, And still the tumult of the trees. Unanxious for tomorrow’s doom, Count all your present joys for gain; And while your youth preserves its bloom, Nor dances, love, or wine, disdain. Oft let the martial field invite, And oft the public walks survey; And punctually attend at night The assignations of the day The secret laugh, delightful charm, Will oft betray the skulking dame; Then snatch the token from her arm, Which, with a kiss, she’ll soon reclaim.",
" In dazzling whiteness, lo! Soracte towers, As all the mountain were one heap of snow! Rush from the loaded woods the glittering showers; The frost-bound waters can no longer flow. Let plenteous billets, on the glowing hearth, Dissolve the ice-dart ere it reach thy veins; Bring mellow wines to prompt convivial mirth, Nor heed th’ arrested streams, or slippery plains. High Heaven, resistless in his varied sway, Speaks!– The wild elements contend no more; Nor then, from raging seas, the foamy spray Climbs the dark rocks, or curls upon the shore. And peaceful then yon aged ash shall stand; In breathless calm the dusky cypress rise; To-morrow’s destiny the Gods command, To-day is thine;– enjoy it, and be wise! Youth’s radiant tide too swiftly rolls away; Now, in its flow, let pleasures round thee bloom; Join the gay dance, awake the melting lay, Ere hoary tresses blossom for the tomb! Spears, and the Stred, in busy camps impel; And, when the early darkness veils the groves, Amid the leafless boughs let whispers steal, While frolic Beauty seeks the near alcoves. Soft as thy tip-toe steps the mazes rove, A laugh, half-mother’d, thy pleas’d ear shall meet, And, sportive in the charming wiles of love, Betray the artifice of coy retreat; And then the ring, or, from her snowy arm, The promis’d bracelet may thy force employ; Her feign’d reluctance, height’ning every charm, Shall add new value to the ravish’d toy.",
" See, Thaliarchus! cloth’d in snow, Soracte rises white in air; Keen frost forbids the stream to flow, And scarce the woods their plumy burden bear. Haste! cheer the piercing season’s cold, Pile high with wood the blazing hearth; Let gen’rous wine, four summers old, Flame from the cask, and crown the board with mirth. To heav’n permit the rest whose will, When wild winds war with wintry seas, Can lull them to a calm– so still, That not a murmur waves the trembling trees. Inquire not of to morrow’s doom To-day account a certain gain While time yet spares thy youthful bloom, Nor scorn sweet love, nor shun the choral train. By day let martial fields delight, Where youth th’ athletic contest prove; And, through the silent hours of night, Soft whisper’d sounds, and sighs of murm’ring love. The laugh, that, bursting from the shade, Betrays the fair-one’s secret stand, The love-pledge from her arm convey’d, Or snatch’d, half-yielded, from her struggling hand.",
" Behold where stands Soracte’s height, With rising heaps of snow grown white! Behold the lab’ring woods; Whose lofty branches can of late Hardly sustain their icy weight! And sharp frost binds the floods. Then largely bring thy faggots forth, High pile them on the blazing hearth, The winter’s cold to thaw; And from thy Sabine two-ear’d jars The wine four summers which declares, Kind T’haliarchus, draw! Be other cares to heav’n consign’d, Heav’n that can still the warring wind Scourging the fowamy sea! Then not the aged wild ash moves Its boughs, nor do the cypress groves A trembling leaf display. What hap shall from to-morrow spring Ask not the days which fate may bring As so much profit prize Thy minutes scorn not, happy boy, In dance and sweet love to employ, While stern hoar-age youth flies. Now to the Martial Field oft bend Thy steps, now public walks attend; Of, at th’ approach of night, Freely indulge the whispers soft When love appoints the hour, and oft Repeat such dear delight. Now let the numph’s sweet laugh reveal What secret corner may conceal The frolic fugitive; Some love-pledge from her arm convey, Or from her finger snatch away, Struggling for what ’t will give."
"Seest thou uprear’d with heights of wintry snow Yon mountain whitening o’er the plains below? That burthen’d droop the lab’ring woods And rigid ice congeals the floods? O Friend! dissolve th’ immitigable sky; Pile the glad hearth and rouze the flame on high; And let a more benignant bowl Dilate to mirth the mellowing soul. Submit the rest to Heav’n whose awful sway The waves enchas’d and warring winds obey And groves that rock’d beneath the blast No more their hoary honours cast. Let no to-morrow’s doubtful cares employ, But score as gain each moment giv’n to joy; Nor from the dance in youth refrain, Nor thou the sweets of love disdain, While sullen age thy bloom of manhood spare Now to the mall and to the ring repair And now at promis’d midnight sweet, The love-stol’n whisper soft repeat Nor less the traitor laugh delight thine ear That welcome speaks the lurking fair-one near Whose pleas’d perverseness faint denies The facile yet reluctant prize.",
" See proud Helvellyn’s stormy brow Is cloth’d with chilling snow; Dishonour’d hangs the leafless bough, The rills forget to flow! Dispel, my friend, the cheerless cold, With faggots trim the fire! Now quaff your ale both stout and old! Around let merry tales be told! To wake the soul to Joy, and kindle gay Desire. Tho’ angry storms obscure the skies, And swell the foaming main, Stern Winter’s scowling blast despise Till Spring returns again! Regardless whether weal or woe To-morrow’s dawn await, This hour, convivial joyance know! Let from the cup libations flow; Nor heed the future frowns of unrelenting Fate! O, seize the blissful hour of Love, Whilst active Youth remains, While from the heart gay currents move, And revel thro’ the veins. Ere Age his snowy flakes has shed Around your youthful brows, By you be festive dances led, By you the social board be spread, Nor Nature’s present joys fastidiously refuse! Now Night her sable curtain draws, And now the blooming maid Will fearless all her love disclose, Beneath its secret shade; The covert, where conceal’d she lies, Her titt’ring laugh reveals, And there you snatch the balmy prize, Her half averted lip denies, When Night’s propitious veil the am’rous theft conceals.",
" See Soracte’s lofty brow, How it glitters in the clouds; See how silver-beaming snow All its forests whelming shrouds; See how e’en the vocal rill, By the frost congeal’d, stands still Now, the piercing cold to tame, Thaliarchus, let the fire, Pil’d with fagots, cheerful flame; And, the genius to inspire, Sparkling wine of generous glow, Large from Sabine goblets flow. To the gods the rest resign; For when, darting from the skies, Roaring tempests lash the brine, See, they nod– the tumult dies; And, secure from storm and flash, Tow’rs the cypress, smiles the ash. All to-morrow’s care forego, Only catch the sweets of life; Every day the Fates allow, Taste, belov’d, love’s blissful strife Stray through walks, wrest sport and dance, Ere old age morose advance. And when from a fragrant bow’r, In the moon-enlighten’d shade, At a fair appointed hour Titters sweet the gentle maid, O then snatch, however coy, From her arm the golden toy.",
" I see the lofty mountain now, All white with heaps of frozen rain, And oaks of many an age below Their pond’rous load can scarce sustain. The streamlet, which, in murmurs mild, Meander’d thro’ the mead before, By winter’s iron finger chill’d, In murmurs now is heard no more. To drive away the brumal air, And warm my soul with thoughts divine, The gladd’ning blaze aloft I rear, And quaff in cups of racy wine. But trust me Flaccus, all is vain To drive from out her caverns rude, Grim melancholy, grief, and pain, Sad imps of green-ey’d solitude. Let him, consum’d by inward rage, Or whom false love has taught to pine, His rage forget, his love assuage, By all the mystic powers of wine. Unanswer’d love and rage within, I know ye not, vile sadd’ning brood, But pangs beyond the power of wine I know, the pangs of solitude. The friend alone of kindred mould, (Vain is the sparkling racy flood,) Can drive away that inward cold, The chill of wintry solitude.",
" See the mountain Soracte! how dazzling bright! How deep is he cover’d with snow! See his labouring woods their vast burden of white Scarcely bear while the floods that in motion delight, Stand in sharp icy fetters below. On the fair blazing hearth now the fresh billet fling, High pil’d, til it melt all the cold And in two handled faggon more bounteously bring, Thaliarchus! the liquor that makes the heart sing From the Sabine cask four witters old. Leave the rest, my good friend, to the gods gracious will; For as soon as their mandates assuage The wild warring winds of the deep, they are still The cypress, and old mountain-ash on the hill, Rock no more with the element’s rage. Then cease to inquire what to morrow may prove But each added day offer’d by chance, To thy profit still turn; (nor life’s blessings above) Disdain in thy youth the sweet pleasures of love, Nor to join in the gay festive dance. Now, ere peevish old age turn thy dark tresses white, By day let the field, and the square, To each pastime and exercise manly invite; And ever, with love’s gentle whisper, at night, To the dear assignation repair. Let the Virgin’s sweet titter, with grateful alarms, From the corner her ambush disclose; Now with rapture invade her soft-struggling charms Nor tear the fond token of love from her arms, Or her fingers that feebly oppose.",
" Behold Soracte’s tow’ring head Buried beneath the drifting snow! That o’er its bending forests spread, Forbids its ice bound streams to flow. Then bring more wood, and rouse the fire, And fill once more the sabine bowl, That sees each carking care expire, And cheers to smiles the anxious soul! Leave to the gods each future care! For they command whate’er they please, The storm that lays the forest bare, Or breeze, that scarcely stirs the trees! Ne’er let the fear of coming woe With anxious doubt your thoughts engage; For soon the charms of youth will go, And sink amidst the gloom of age. While youthful joys and sports invite, O catch the moments as they roll! Or, shelter’d by the shade of night, Breathe in love’s ear th’ impassioned soul. A titt’ring laugh your steps will bring, Where ill conceal’d the fair one lyes; There, struggling coyly, sieze her ring, While she with blushes yields the prize!",
" See, see, the woods are clad with snow, The lagging streams have ceas’d to flow Then come, my jolly host, Ring for some coals, for in these days I love to see a cheerful blaze To calm the ungenial frost. And Hal, since now once more, my friend, We’re met, a jovial hour to spend, From out your richest hoard, Let’s have some generous Port (which there In sawdust’s moulder’d many a year) To grace your social board, With such delight-inspiring cheer, We’ll to the winds each trivial care, Each boding sorrow throw And whilst to-night we joyous sing, On what the morrow’s dawn may bring We’ll not a thought bestow. For now’s the time, ere youth is fled, To join the dance with airy tread, And hail fair Pleasure’s birth Ere fretful age, with tottering knee Frowns on these scenes of revelry, These transient hours of mirth, New too, our ardent youth conspires To fan the flame of soft desires, Rais’d by the dart of Love; To snatch the short extatic bliss Found in the ardent stolen kiss A gentle frown reproves.",
" See’st thou yon mountain laden with deep snow, The groves beneath their fleecy burthen bow, The streams congeal’d forget to flow; Come, thaw the cold, and lay a cheerful pile Of fuel on the hearth; Broach the best cask, and make old Winter smile With seasonable mirth. This be our part– let heaven dispose the rest; If Jove command, the winds shall sleep, That now wage war upon the foamy deep, And gentle gales spring from the balmy west. E’en let us shift to-morrow as we may, When to-morrow’s past away, We at least shall have to say, We have liv’d another day; Your auburn locks will soon be silver’d o’er, Old age is at our heels, and youth returns no more.",
" Soracte’s summit’s white with snow Huge loads depress the groaning woods And keen and lasting frosts have now Congealed the rapid rippling floods. Dissolve, my friend, the piercing cold With faggots light a cheering fire Bring forth thy wine of four years old, To raise thy drooping spirits higher. Commit the rest to almighty Jove; And, when he’s hushed the winds that brave The fury of the main, the grove Will cease its shivered arms to wave. Beware of brooding on to-morrow The span that fate allows enjoy Nor e’er refuse to banish sorrow, By love and pleasure, blithesome boy. Ere age begin thy mind to sour, Now wrestle on the martial plain; Now, at a fixed nocturnal hour, With gentle whispers soothe thy pain. The laugh, betrayer of some coy Fair spinster, in a nook concealed, The pilfering of some pledge, enjoy, From her affecting not to yield.",
" Seest thou Soracte white with snow? The ice-bound streams no longer low, The labouring woods resound. Let high-piled faggots drive the cold, And Sabine wine, four winters old, More cheerfully abound. O, Thaliarchus, leave the rest To mighty Jove’s unerring breast He bids the storm to cease No longer then, in angry mood, The winds shall battle with the flood, And groves shall rest in peace. Seek not to know to-morrow’s fate; The present day, with heart elate, Consider as a gain Nor Dance, nor jocund Loves despise, Till peevish, snowy locks arise, And age begins his reign. Now camps and theatres delight, And gentle whispers to the night The hours appointed bring; Now from the finger of the fair, Who flies, but laughs, and tells you where, Is snatch’d the willing ring.",
" Seest thou, Taliarchus, the waving brow Of huge Soracte, stiff with circling snow, The woods that groaning bend ’neath winter’s force, And the sharp ice that stays the streamlet’s course? Then, let thy hearth its cheering warmth expand, And heap the hoarded log with lib’ral hand, In Sabine cup bring forth th’ enliv’ning wine, Which four revolving years has caus’d to shine; And since the gods have lull’d the whirl-wind’s roar, That urg’d the foaming wave against the shore, And given the aged elm and cypress rest, Submit all else to them– with this be blest; Think every day a gift the gods bestow, What the dark future hides, seek not to know; And chiefly while old age delays to spread His silv’ry honours o’er thy youthful head, Court the inspiring Muse’s sacred fire, And thread the mazes to the warbling lyre. Display in martial sports thy active power, And breathe soft whispers at eve’s chosen hour.",
"See’st thou, my friend, how white with snow Towers in mid air Soracte’s brow; How with their load the forests bend, And frost the torrent’s force has chain’d! The season’s chilling cold to chase, Bid on thy hearth huge fagots blaze; And from the twin-ear’d pitcher pour Thy inmost bin’s time-mellow’d store. Leave to the Gods all cares beside Soon as their voice has quell’d the pride Of storms wild-howling o’er the sea, Stirs not a breath the aspen-tree. To trace to morrow’s doom forego, And count as gain each granted Now Nor thou the joys of Love’s young morn, Or dance of sprightly damsels scorn, While still with gray unstain’d thine hair Now to the public mall repair, Assiduous; in th’ appointed bower Now breathe thy tale at eve’s soft hour. Dear now the titter arch, which tells What nook the ambush’d maid conceals; Sweet from the struggling yielding fair The ring, or bracelet-pledge, to tear.",
" Soracte, clad in Winter’s snow, Lifts high his silv’ry head; See rivers frozen cease to flow, And trees their leaves have shed. Now Thaliarchus stir the fire, Heap high the wood upon the hearth; Let Bacchus ev’ry breast inspire, And banish cold with pleasing mirth. Leave to the gods with quiet mind What else may thee betide; Whose word can still the stormy wind. Which swells the waters wide. At whose command the lofty ash, And noble cypress spreading far, No more with angry murmur clash, Nor leave their shaken branches bare. Seek not to know with anxious care How long thy life may be! What future days may be thy share, Those days ’count gain to thee. In the bright glowing morn of youth, Let pleasures gay employ thy hours; Ere cruel Time’s relentless tooth Hath deaden’d all thy vig’rous powers. Oft in the field of Mars display Thy strength and polish’d limbs; Then to the theatre thy way Exulting take betimes. Seek too the dulcet voice of Love, Which soft is as the evening breeze, Whose soothing hush can scarcely move The gently-agitated trees.Full oft the merry laugh betrays The playful hidden girl; Whose bracelet then the forfeit pays, Or ring of shining pearl. With feign’d regret the blushing Maid On her rapt bracelet seems to look, And much she grieves the laugh betray’d Her hiding in the darksome nook.",
" See! how Soracte’s hoary brow And melancholy crags uprear Their weight of venerable snow And scarce the groaning forests bear The burthen of the gloomy year And motionless the stream remains Beneath the weight of icy chains. Thou of the social banquet King, Now store of welcome faggots bring, Now bid a brighter flame arise, Now let the rich and rosy wine Within the joyful goblets shine, That wine whose age hath seen the ray Of four long summers roll away Along yon wintry skies. Leave to the Gods the rest– whose force Can stay the whirlwind’s wasting course; When they have soothed the maddening jar Of mingled elemental war, Nor those tall ash-trees dread the storm Nor cypress bows his shadowy form. Why should we fear tomorrow’s woe? Whatever day the Powers above Have given, rejoice nor, while the flow Of joy and golden youth delight Thy soul– while age avoids thee– slight The mazy dance– the power of love.",
"’Tis winter now– how cold and chill! See, how the loads of snow Have wreathed the top of yonder hill, And bent the forest bough; And murmuring streams, which o’er the green Sent liquid melody, Now silenced by the winter keen, In icy calmness lie. But, heedless of the bitter cold, Come, gather round the fire, And see if Sabine, four years old, Can jollier thoughts inspire For only such as spring from drinking Are worthy of our love; Then leave all dull and needless thinking To those who dwell above They swell the storm– but when again They would its rage recall, No more is tossed the hoary main, Nor rent the cypress tall. Then, while yon can, with generous wine Defend your heart ’gainst sorrow, Nor e’er bestow one thought of thine Upon the coming morrow. And while the bloom is on thy cheek, And auburn is thy hair, The merry dance at evening seek, By night thy mistress fair. Then, at the hour to Cupid dear, Fly to th’ appointed spot, And while the careless jilt you fear May have her love forgot Then the sly laugh, from your dear maid, Shall tell where she’s concealed And from her arm take ’neath the shade, The pledge she half would yield.",
" See Mount Soracte crown’d with snows, Whose weight its woods can scarce sustain, The gelid stream no longer flows, And Nature owns the wintry reign! Come chase the cold, and heap the hearth, Give loose to joy, give loose to mirth, And let the goblet’s copious brim With wines of richest vintage swim; And leave, my friend, the rest to heaven, Who this congenial calm has given, And stills the winds that swept the seas, And soothes to rest th’ unmoving trees. Nor let the future give thee sorrow, How to provide the coming morrow; But now, while age yet lingers late, And health and youth are all elate, Indulge what joys to youth belong, And taste the charms of love and song; For courts and fields become thee now, And whisper’d sound of lover’s vow, And gentlest laugh of sportive maid, In corner hid, and thus betrayed; And pilfered ring, scarce known to linger On playful Beauty’s yielding finger.",
" Bleak Soracte meets my sight, Clothed in a robe of virgin white; The olives in the vale below, Groan beneath a load of snow, While bound in strongest bands of frost, The currents of the streams are lost, One solid sheet of ice spreads o’er, Fair Tyber’s banks from shore to shore. Dispel the cold, the friendly blaze, To warm and cheer your poet, raise; With wood the blazing ingle crown, Till every object shine around. From Sabine cask thy nectar pour, To beguile the weary hour, Cause the sparkling goblets shine, With four years old Falernian wine. The cares of life, the pangs of love, Leave them to the gods above, Who calm the storm, and still the breeze, Contending with the stormy seas, When the dark cypress groves are still, And the old beeches ’neath the hill. What cares sit on to-morrow’s brow, Leave off to seek the sequel now; What length of days to thee are given, Contented wait the will of heaven. Fond youth, disdain not love’s advances, When proffer’d thee, nor yet the dances, Till crabbed age above thee hover, And thy hey-days of youth are over. Now Campus Martius, and the streets Of ancient Rome (where each whisper meets The ear, when evening shadows lower), Are sought again at the appointed hour; And the coy maid’s light-hearted smile, Her feign’d retreats too soon beguile. On her arms the bracelets feebly linger, And the ring on her gently resisting finger.",
" Lo! on the mountain’s awful brow, A vast augmenting mass of snow, The woods can scarce their load sustain; The streams no more pursue their course, But, held by Winter’s griping force, Are fix’d within his icy chain. Pile faggots on thy blazing hearth, Devote the passing hours to mirth, Nor heed, oh! friend, the season’s war; Still better to subdue the cold, Bring gen’rous wines four summers’ old, And let us drain the Sabine jar. Trust to the gods the rest when they Shall drive the boist’rous wirds away, That range along the foaming main, No longer then the Cypress grove, Nor aged ash, in storms shall move, But Peace o’er all resume her reign. Seek not to scan, with curious eye, What in to-morrow’s fate may lie, But count as gain the present day, Nor, while the fires of youth remain, Refuse to join the dancing train, Or with the smiling loves to play. Now to the martial field remove, Or public walk, or private grove, When night her mantle spreads around, While, gentle as the vernal airs, Soft whispers speak enamour’d pairs Before th’ expected signal’s found. Now, too, the charming laugh to hear That proves the partial damsel near, Who seems to fly, with anxious care, Affecting to resent with scorn What fondly from her arm was torn, And hides, yet laughs to tell thee where.",
" See! whiten’d into whelming snow, Begirt with crouching woods below, Soracte’s mountain form; And, lock’d by winter’s icy hand, How currentless the rivers stand! Then heap the hearth with blazing piles! Let winter melt amid their smiles, And generously bring Your mellow’d wine, the best by far That flourisheth in Sabine jar. My Thaliarchus, trust the god Who rules the ocean with his rod, And lays the winds asleep; Till, in one leafy slumber bound, The warring trees are hush’d around! Whate’er to-morrow’s hue may be, The living day is life to thee; A treasure for the soul Enjoy the reign of laugh and love, And all that virgin dances prove. While yet unworn by wintry years Thy cheek a blooming manhood wears, The martial plain be thine! Or haunted path, or twilight seat, Where faltering lips their love repeat For now the laugh’s delicious wile From lurking damsel, hid a while In some betrayful nook; And pretty theft of token charms When forced from her forgiving arms.",
" Behold how, on the lofty brow Of lone Soracte, stands the lustrous snow! Ill bears its load the labouring wood, And creeps the sharp ice through the halting flood. Dissolve the cold!– the hearth shall smile, Heaped– largely heaped– with many a blazing pile! Come, Thaliarchus, bid the wine, Some four years old, in Sabine goblets shine! Leave to the Gods the rest, who still Loud winds with waters battling, at their will; So that at last no angrier breeze Stirs the wild ash, or waves the cypress-trees. The future of the morrow shun, But count true gain with each revolving sun, Nor spurn, till age green joy Makes chill– soft love, or choral dance, fair boy! Thee shall blithe sports please now, And blandest whispers, nightly murmured low; And the glad laugh from coyish maid Hid in some nook, (that laugh the nook betrayed;) And Love’s dear pledge– the armlet band, Or ring, hard won from dear, reluctant hand!",
"See tall Soracte white with snow! The forests groan beneath their load; The imprison’d streams no longer flow, Through crystal caverns working slow Their hollow winding road. Stern winter’s call, my friend, obey! Pile high thy blazing hearth with wood; And, more to drive the cold away, Let thine old Sabine cask to-day Pour forth a nobler flood. Be this thy care! the rest resign To heaven, that stills the tempest’s roar, That bids the winds their rage confine, And the tall ash and mountain pine Toss their proud heads no more. Repress the fondly curious glance That fain would scan the future hour! Improve each day’s revolving chance, Nor shun the soul-enlivening dance, Nor love’s enchanting power. Be thine– while age yet spares to blight The verdure of thy youthful bloom The chase by day, the ball by night, And amorous whispers, warm and light, Soft stealing through the gloom. The laugh, too ready to betray The lurking girl who fain would hide; The bracelet gaily snatch’d away, Which, half in earnest, half in play, Her struggling arm denied.",
" See’st thou not amid the skies, White with snow, Soracte rise? While the forests on the plain Scarce their hoary weight sustain, And congealed the waters stand Neath the frost’s arresting hand. Drive away the winter wild; On the hearth be fuel piled; And, from out its inmost cell Kept in Sabine vase so well, Generous, bring thy four years wine; Brightest source of song divine! Wisely leave the rest to heaven, Who, when warring winds have striven With the forests of the main, Bids theit ragings rest again. Be not ever pondering Over what the morn may bring; Whether it be joy or pain Wisely count it all as gain; And, while age forbears to shed Snows, or sorrows o’er thy head, Do not scorn the dancers’ feet, Not thy lovers dear retreat. Hasten to the plan or square; List the voice that whispers where, While the calm night rules above, Thou may’st meet thy constant love; While the laugh round corner sly May instruct thee where to spy; While the wanton’s feigned retreating Still may leave some pledge of meeting; Perhaps a ring or bracelet bright Snatched from arm or finger white.",
"How white Soracte stands, behold, With lofty snows! Its labouring trees Groan ’neath the weight. The rivers freeze And flow no more, congeal’d by cold. Replenish largely from your store The fire with logs, dispel the chill; And wine, the cherish’d four-year old, From Sabine cask more freely fill. Leave to the gods the rest whose word, Soon as it lulls the boiling seas Battling with winds, the cypress trees, And aged elms, no more are stirr’d. Ask not, to-morrow what may chance, Count it for gain whate’er betide; Nor spurn, to peevish age denied, Soft loves, my boy, nor yet the dance Whilst hoary age, morose and sour, Spares thy green spring, youth’s pastimes light By day, soft whisperings by night, Be thine, at the appointed hour, The hiding maid’s forced laugh, dear sound, From secret nook, love’s fond alarm; The pledge, which beauty’s plunder’d arm, On irretentive finger bound.",
" You see Soracte’s alpine-height, With gath’ring snows stands clad in white, Nor labouring woods the weight can bear, Streams stagnate in the gelid air. Dissolve the frost of winter’s dearth, With billets pile the social hearth, Free Thaliarchus, now draw forth Rich Sabine juice of four years’ birth, Leave to the guardian powers the rest, Who gusts tempestuous have suppress’d With fervid ocean late which strove, Nor cypress now, nor ash-trees move. Avoid to-morrow’s luck t’enquire What fortune shall bestow, admire, Count it a token sure for gain; Nor, since a jocund youth, disdain In love’s delightful sports t’ engage, While hoariness shuns blooming age To Horse-guards and the Mall repair, Soft whisp’rings with th’ appointed fair; Let the delightful laugh betray The damsel hiding for your play; With token from her finger won, She vows t’ have set her heart upon.",
" See, with the deepening flakes, how white Soracte stands!– the woodland height Can scarce sustain the weight of snow, While ice-bound rivers cease to flow. Dissolve the cold– with logs pil’d high Now plenteously the fire supply; And from thy Sabine cask produce– Now four years old– the mellow’d juice. Leave to the gods the rest– when they The battling winds and waves allay, Nor ancient ash, nor cypress more Shall dread the tempest’s angry roar. Unsought the morrow’s fate remain, But count the accorded day as gain; Nor spurn the dance, nor love’s sweet vows, While whiteness spares thy youthful brows. Now for the Campus, and the park! The gentle whisperings after dark! The assignation!– Now the maid, By laughter’s merriest peal betray’d, Quits the sly corner where she watch’d See, from her arm the pledge is snatch’d! While now her finger yields the prize, She half accords– yet half denies.",
" See, how old Soracte’s height Stands with snowy mantle white, How the forest’s labouring bough Scarce sustains its burden now, And the river’s flow is lost, Stiffen’d with the icy frost. Dissolve the cold; upon the fire Pile the ample faggot higher And in thy two-ear’d Sabine bowl, O Thaliarch, with liberal soul, From thy cellars draw profuse The four-year-old’s emmellow’d juice. Leave unto the Gods the rest They, as soon as their behest Has lull’d the tempest winds to sleep, Struggling with the boiling deep; Nor aged ash nor cypresses Are longer shaken by the breeze. What to-morrow may transpire, Seek, oh! seek not to inquire; Every day that we obtain From Fortune, set it down as gain; Nor, my boy, disdain to prove The joys of dancing, or of love, While old age, morose and gray, Keeps from thy green youth away. Now oft and oft frequent again The publie walks, the Martial plain, And whisper’d vows at night repeat, When at the chosen hour you meet. And let there oft repeated be The giggling laugh of maiden glee, Betraying where the damsel lies In yonder nook, while love’s sweet prize Is from her arm or finger reft, Which ill resents the wish’d-for theft.",
" Thou seest how Mount Soracte stands, Its summit white with glistening snow; And how the laboring forests seem Under their pressing load in bow And held by winter’s icy hand All motionless the rivers stand. By heaping wood upon the fire Dissolve the season’s piercing cold; And freely from the Sabine jar Draw out the pure wine four years old; And, Thaliarchus, thus the day Careless in pleasure pass away. And to the gods give up the rest; For when upon the stormy deep The warring winds by them are calmed, Nor ash trees on the mountain steep, Nor yet the lofty cypress trees Are moved by e’en the slightest breeze. And what the morrow’s fate shall be, Seek not with anxious heart to know; But every day which fortune gives, Enjoy before its hours shall go. Nor shun, while young, the joyous dance; Nor spurn the Muses’ favoring glance; As long as hoary age morose Is absent from thy blooming years, Now seek the public squares again Again frequent the field of Mars; At eve, the appointed time, oft meet Thy love, and whispers soft repeat.",
"Canst thou not see Soracte’s whitening crest And feathered forests bending to the snow, While bitter frosts the onward course arrest Of streams no longer rippling as they flow? Dispel the cold, heap logs upon the flame; And, Thaliarchus, push around the board, Plenty of mellow Sabine wine– the same, The two-eared cask, four ripening years hath stored. The rest leave to the Gods; it is for them To lull the winds that lash the boiling seas When calmed, no leaf upon the cypress stem, No ashen twig, shall quiver in the breeze. What shall to-morrow bring, forbear to ask; Place to the good the pleasures of to-day; And, youthful still, spurn not love’s gentle task, Nor merry dance to while the hours away. Ere hoary age hath ploughed thine ivory brow, While still the public walks thou’rt fit to grace, And breathe in listening ear the whispered vow, And punctual seek the nightly trysting place; Whilst hide and seek with laughing maids can charm, And forfeits from the willing to demand, The bracelet loath to leave the snowy arm, The ring much pressed to quit the yielding hand.",
" Thou seest how Soracte stands, Glass’d over with its depth of snow; Nor may the groaning labouring woods Hold up beneath their burden now; And streams in masses ’neath the force Of the sharp frost have stopp’d their course. Thaw thou the cold; with bounteous hand The logs upon thy hearth-fire heaping; And kindlier draw from Sabine jar Thy luscious wine of four years’ keeping; O Thaliarchus! all beside Surrender to the gods to guide. For, soon as they have laid the winds, That battle fierce with seething ocean, Nor cypresses, nor mountain ash Timeworn are toss’d in wild commotion. What on to-morrow there shall be, Eschew from searching curiously. And what amount of days thy lot Shall grant thee, set it down to gain; Nor do thou sweet delicious loves, Nor dances, thou a boy, disdain; While from thee, in thy spring-tide gay, Hoar churlish eld afar doth stay.",
" See how white Soracte stands Deep of snow! the staggering trees No more support the load the rivers Halt, in frosty stiffness fetter’d. Melt the cold with plenteous logs Heap the hearth from Sabine jar, O Thaliarchus, largely grant me Wine that four full years have mellow’d. Leave the gods to guide the rest. Gales contend; and Ocean boils But when the gods rebuke the turmoil, Mountain-ash nor cypress quivers. Shun to ask the morrow’s lot Every day bestow’d by fate Compute as gain; and, fresh in boyhood, Scorn not tender loves and dances. Hoary sternness soon will come Now the field, the course, the mall, Demand thee now let gentle whispers Find thee true to hours appointed; Or the hidden damsel’s laugh, Telltale sweet, from deep recess; And pledges torn from arm or finger Little grieved to lose its treasure.",
" You see Soracte with deep snow Stands white, nor labouring forests now Sustain their load; each running rill, Arrested in its course by the keen frost stands still. To thaw the cold the faggots pile Upon your hearth; more free the while, O Thaliarchus, bring us up Your wine, now four-year-old, in two-ear’d Sabine cup. Leave to the gods the rest; for when The winds at war with the chaf’d main They have appeased, the cypress grove Is tossed no longer then, nor ancient roan-trees move. What shall be next seek not to know, But each day’s product score up thou As present gain; nor, yet a boy, Disdain the sweets of love and dances to enjoy, While blooming still, nor o’er thy head The peevish hoar of age is spread. At eve’s concerted hour, the Plain, The squares, and whispers soft, be sought by thee again; And welcome laughter of the maid, Thus in her inmost nook betray’d, Where waiting thee concealed she lingers, The pledge snatch’d from her arms and ill-reluctant fingers.",
"Behold old Soracte, his brow is o’erspread With the chill veil of winter, the fleecy white snow; The woodland is bowing its wearisome head, And the ice-fettered rivers have long ceased to flow. Crown thy hearth, Thaliarchus! with brilliant fires high, Till the chill airs of night shall have fled from thy dome, Then the sabine vase fill with a richer supply, And around the glad board let the racy wines foam. Leave the rest to the Gods, at whose will the loud blast As it howls in its wrath o’er the ocean’s rough breast, Is hushed; while the ash and the cypress that cast Their boughs to the skies, find a season for rest. O care not to know, my old Friend! what the morn Of tomorrow may bring, but still deem thyself blest, For each day fate bestows, nor look on, as in scorn, The gay festive dance, nor the ones we love best. While thy youth, strength, and beauty, are all in their bloom, On the wide open field, or within the dark lane While the slow shades of Ev’ning are spreading their gloom, Breathe the lover’s soft whisper again and again. And still hear the laugh that betrays the wild fair, As away from her lover she wantonly flies, And the love-token seize, which, with lov’liest air, Her willing heart yields, tho’ her sweet voice denies.",
" Dost thou not see Soracte’s height With depth of snow is dazzling white? The woods no more their weight sustain, The streams are bound in icy chain. Dissolve the cold, while on the dogs With lavish hand you fling the logs, And, Thaliarchus, from your store The four years’ wine more freely pour. Trust with the gods the rest, whose will Can bid the warring winds be still, Cypress and ancient ash tree cease Their strife, and lift their heads in peace. Seek not the morrow to foresee, And each fresh day, whate’er it be, Deem so much gained, nor, madly wise, Oh, Boy, the dame of love despise. Ere hoary Age, morose, uncouth, Check the free sports of blooming youth, Let gentle whispers, low yet clear, Breathe in soft Twilight’s secret ear While shrilling forth from darkened shade The laugh betrays the lurking maid, Then from white arms be bracelets torn, From fingers rings too loosely worn.",
" Seest thou Soracte, deep in snow, stands white, The labouring woods can scarce sustain their weight, And sharp the frost arrests the river’s flight. Let logs in plenty on the fire combine The cold to scare, with free-drawn four year wine, O Thaliarchus! from the jar Sabine. To gods the rest! who making calm to be, The winds contending with the boiling sea, Nor mountain ash shall shake, nor cypress tree. From seeking what to-morrow haps abstain, The days that fortune gives, place thou to gain, Nor gentle loves, my boy, nor dance, disdain. White age afar, and thou robust, review The Campus Martius and the halls anew, And whispers soft at night’s fixed hour renew. Now also seek, by pleasant laugh betrayed, In spot remote, to snatch from hiding maid The pledge, from arm or finger, shamly staid.",
" Behold how whitened with the deep snow remains Soracte; nor more lab’ring the wood sustains Its weight incumbent; and congealed Stands ev’ry stream by the hard frost sealed! The cold dispel thou, bounteous with many a brand The hearth up-piling then with a lib’ral hand Bring thou the four-years’-vintage wine forth, O Thaliarchus, from jar Sabine forth! The rest resign thou unto the Deities When they the wind calm, as with the boiling seas It struggles, nor the aged ashes Then, nor the cypress it longer lashes. To-morrow’s fortune ever to seek refrain The day that Fate grants ever account as gain Nor, while a boy, of love’s sweet pleasures Heedless be thou, or the dance’s measures, As long as grim age from thy green youth abstains. ’Tis now the time for parks, and for martial plains; At night-fall, too, the whispered greeting At the appointed hour oft repeating. And now the pleasing laugh of some youthful maid Hath her retired nook where she was hid betrayed And from her arms a pledge she loses, Or from her finger that scarce refuses.",
"Behold Soracte, white with snow, Its laden woods are bending low, Keen frost arrests the river’s flow; Melt, Thaliarchus, melt the cold. Heap freely logs upon the fire. Nay, more and better I desire, And from that Sabine jar require Its wine, that reckons four years old. The rest is Heav’n’s: which can at will Bid all the battling winds be still Upon the seething main; until Nor veteran ash nor cypress quake. Pry not, the morrow’s chance to learn: Set down to gain whatever turn The wheel may take. Youth must not spurn Sweet loves, nor yet the dance forsake, While grudging Age thy prime shall spare. The Plain, the Squares, be now thy care, And lounges, dear at nightfall, where By concert love may whisper Hist! From inner nook a winsome smile Betrays the girl that sculks the while, And keepsakes, deftly filched by guile From yielding finger, or from wrist.",
"See how the storm-drifts glimmer white On far Soracte’s craggy height, And scarce the labouring woods Sustain th’ unwonted load of snow, While icy fetters in their flow Arrest the silent floods! Oh, Thaliarchus, pile up higher The blazing logs upon the fire, And thaw this wintry cold! Then from thy cellar’s inmost shrine Bring freely forth thy choicest wine, In jars of Sabine mould! We’ll drink, and leave the rest to Heaven, Whose mandate is no sooner given To calm the raging seas, Than straight the winds have ceased to pour Their fury on the sounding shore Have ceased to rend the trees! Ask not too curiously if sorrow Perhaps await thee on the morrow, But each successive chance Convert to profit; nor remove From thy young heart the sweets of love, Nor shun the festive dance. But while morose Old Age may spare Thy blooming cheek and flowing hair, Now let the sunny plain, Or public square or serenade, In honour of some blushing maid, At eve be sought again. The girl’s low laugh, by which we trace The secret of her hiding-place, Delights the youthful ear; Nor less the ring or bracelet ta’en From hands that struggle but to feign, To youthful hearts are dear.",
" Behold, Soracte’s peak is crown’d, My Thaliarch, with snow! The drooping branches sweep the ground, And, fast in icy fetters bound, The streams have ceased to flow. Pile up fresh logs upon the hearth, To thaw the nipping cold, And forth from Sabine jar, to wing Our mirth, the ruddy vine-juice bring Four mellowing summers old. Leave to the Gods what else may be; When they have still’d the roar Of winds that with the yeasty sea Conflict and brawl, the cypress tree, The old ash shake no more. Let not to-morrow’s change or chance Perplex thee, but as gain Count each new day! Let beauty’s glance Engage thee, and the merry dance, Nor deem such pleasures vain! Gloom is for age. Young hearts should glow With fancies bright and free, Should court the crowded walk, the show, And at dim eve love’s murmurs low Beneath the trysting tree. The laugh from the sly corner, where Our girl is hiding fast, The struggle for the lock of hair, The half well pleased, half angry air, The yielded kiss at last.",
" See, Thaliarch, how deep in snow Soracte stands, the labouring woods Bend with their load, and wintry floods, Benumb’d with frost, forget to flow. Heap log on log the spell to thaw: Shall winter’s frown our banquet mar, Or from thy raciest Sabine jar Brimful the generous magnum draw? Commit the rest to Jove’s high hand: At the first bidding of his will The wave and brawling wind are still, Erect the ash and cypress stand. Why, curious, turn the morrow’s page? Set down as gain whatever chance The day affords; enjoy the dance, Make love; full soon will peevish age Put such toys by. Now let us go Where open square and public walk Buzz all around with whisper’d talk And sighs at nightfall breathing low: Thence track the scarce reluctant maid By laughter to her form, and snatch From arm or hand the ring to match, Whereon sweet forfeit must be paid.",
" Seest thou Soracte, glistening with snow, The loaded woods, the rivers ceased to flow? Be warm at home; with logs heap high the fire, Freely let wine mirth, Thaliarch, inspire. Trust in the gods; when pleaseth them, the seas, The winds are hush’d, nor rock’d the forest trees. Think not the ill to-morrow may bring forth, Of present joy appreciate the worth. Strike up the dance, the viol and the song; Youth, snatch the pleasures that to youth belong! The course, the chase, may spring-time hours delight, The social feast, but most the rapturous night. Nut-brown thy locks, in softer sports engage, Far yet awhile the peevishness of age. In corner sly the damsel’s treacherous laugh Her fearful joy betrays, consenting half. Dare then to loose her bracelet’s yielding spring, Or spoil, love’s pledge, the finger of its ring.",
" Soracte’s peak is white with snow, The trees yield to its force, The river now has ceased to flow, Arrested in its course. Then heap the logs upon the fire, Its influence is benign; Grant, Thaliarchus, our desire, And pour out Sabine wine. Let none reflect or seek to know About their future state, But join the dance and games of chance, While it is not too late. Through the delightful days of youth Be happy while you may, Too soon gray hairs and carking cares Will tell of your decay. Then take a ring from the gentle hand, A bracelet from the arm, Or steal a kiss, far greater bliss, Despite their feigned alarm. Heap on more wood, the storm is fierce, The tempest rages higher, But we’ll not mind the storm and wind While sitting ’round the fire.",
" One dazzling mass of solid snow Soracte stands; the bent woods fret Beneath their load; and, sharpest-set With frost, the streams have ceased to flow. Pile on great faggots and break up The ice: let influence more benign Enter with four-years-treasured wine, Fetched in the ponderous Sabine cup: Leave to the gods all else. When they Have once bid rest the winds that war Over the passionate seas, no more Grey ash and cypress rock and sway. Ask not what future suns shall bring. Count to-day gain, whate’er it chance To be: nor, young man, scorn the dance, Nor deem sweet Love an idle thing, Ere Time thy April youth hath changed To sourness. Park and public walk Attract thee now, and whispered talk At twilight meetings pre-arranged; Hear now the pretty laugh that tells In what dim corner lurks thy love; And snatch a bracelet or a glove From wrist or hand that scarce rebels.",
" Lo, white Soracte, deep in snow, The streams all bound in icy chains, The loaded forest, bowing low, Its frozen burthen scarce sustains. Shut out the cold– and quick prepare Wood, largely, on thy hearth to throw; Then, bring out, in a Sabine jar, Wine that was press’d four years ago. All else trust to the Gods: for they Can make the winds and waves be still, And not one leaf can go astray, From oak or cypress, if they will. What chance to-morrow has in store, Seek not to know: but let it be Suflicient that thou mayest score To-day, as so much gained by thee: Whilst yet a youth, frequent the dance, Cast not the joys of love away; Wait not the eve of life’s advance, Nor till thy head is tinged with gray. Now, sports, and public walks attend, And when th’appointed hour is near, To meet, at eve, some gentle friend, Go, whisper softly in her ear: ’Tis now the merry laugh assists The hidden maiden to betray, When, from her hand, that scarce resists, Some trinket you can snatch away.",
" Mark how upon Soracte’s height The snow lies deep; how lab’ring woods Beneath th’ unwonted burthen bow; How stay their course th’ imprison’d floods. Pile, Thaliarchus, pile on high The blazing logs, and mock at cold: This gen’rous flagon freely ply Of Sabine vintage four years old. Leave to the Gods all else: when they Compose the warring winds and seas, The cypress bough, the ashen spray, No longer quiver in the breeze. Think for the morrow nought; enjoy Each day the boons bestow’d by chance; Nor rudely spurn, too happy boy, Or love’s delights, or joyous dance, While crabbed age is far away. Now manly sports beseem thy years, And whispers soft, at close of day, How sweetly breath’d in willing ears And tell-tale laugh of merry maid In corner hid; and slender wrist Of bracelet spoil’d, or ring convey’d From fingers that but half resist.",

]





# Preprocess text: Remove punctuation and convert to lowercase
def preprocess(text):
    return text.translate(str.maketrans('', '', string.punctuation)).lower()

translations_clean = [preprocess(t) for t in translations]

# Extract first 3 words for labeling
def get_first_three_words(text):
    return ' '.join(text.split()[:3]) if text else "[No Text]"

labels = [f"Version {i+1} ({get_first_three_words(t)})" for i, t in enumerate(translations)]

# Create n-gram vectorizer and compute n-gram similarity
vectorizer = CountVectorizer(ngram_range=(2, 3)).fit(translations_clean)
ngram_matrix = vectorizer.transform(translations_clean)
similarity_matrix = cosine_similarity(ngram_matrix)

# Perform hierarchical clustering
num_clusters = min(len(translations), 10)  # Adjust dynamically based on number of translations

# Create an undirected graph using NetworkX
G = nx.Graph()

# Dynamic threshold based on top N% of similarities
top_percent = 0.015  # Keep top 5% of strongest connections
sorted_similarities = np.sort(similarity_matrix.flatten())[::-1]
threshold = sorted_similarities[int(len(sorted_similarities) * top_percent)]

max_weight = np.max(similarity_matrix)
min_weight = np.min(similarity_matrix[similarity_matrix > threshold])

# Add undirected edges based on dynamic threshold
for i in range(len(translations)):
    for j in range(i + 1, len(translations)):
        if similarity_matrix[i, j] > threshold:
            G.add_edge(i, j, weight=similarity_matrix[i, j])

# Filter nodes to only those with significant connections
significant_nodes = {node for node, degree in G.degree() if degree > 0}
G = G.subgraph(significant_nodes)

# Draw the network graph
fig, ax = plt.subplots(figsize=(12, 10))
pos = nx.kamada_kawai_layout(G)

# Draw undirected edges with color representing similarity strength
for i, j in G.edges():
    edge_color = (similarity_matrix[i, j] - min_weight) / (max_weight - min_weight)
    nx.draw_networkx_edges(G, pos, edgelist=[(i, j)], edge_color=plt.cm.coolwarm(edge_color))

# Draw nodes
nx.draw(G, pos, with_labels=False, node_color='blue', node_size=500)

# Draw labels
for i, (x, y) in pos.items():
    plt.text(x, y, labels[i], fontsize=8, ha='right', bbox=dict(facecolor='white', alpha=0.7))

plt.title("Translation Similarity Network (Undirected)")
plt.show()

# Print versions in descending order of similarity to others
influence_scores = similarity_matrix.sum(axis=1)
sorted_indices = np.argsort(influence_scores)[::-1]

print("Versions ranked by similarity to others:")
for idx in sorted_indices:
    similar_versions = [labels[j] for j in np.argsort(similarity_matrix[idx])[::-1] if similarity_matrix[idx, j] > threshold and j != idx]
    print(f"{labels[idx]}: similar to {', '.join(similar_versions)}")

# Group translations into sets of 20 and plot average similarity over time
group_size = 7
num_groups = len(translations) // group_size + (1 if len(translations) % group_size != 0 else 0)

average_scores = [np.mean(influence_scores[group * group_size: min((group + 1) * group_size, len(translations))]) for group in range(num_groups)]

plt.figure(figsize=(12, 6))
plt.plot(range(1, num_groups + 1), average_scores, marker='o')
plt.xlabel("Group of Seven Translations")
plt.ylabel("Average Similarity to Other Versions")
plt.title("Average Similarity of Translations Over Time")
plt.show()
